### ISSUE TITLE
gitignore file with one more . 

### ISSUE THREAD

**Issue by xxholly32** [ulivz/create-vuepress#1]
`
https://github.com/ulivz/create-vuepress/blob/master/lib/generators/blog/templates/_.gitignore
` ->

`
https://github.com/ulivz/create-vuepress/blob/master/lib/generators/blog/templates/_gitignore
`

otherwise gitignore file with two dots

**Comment by ulivz** [comment]
Thanks for the report, fixed at 6e607ff and published at `0.0.10`
